### ISSUE TITLE
Wrong RC time for the turn on of the upper FET in file "design-notes.md"

### ISSUE THREAD

**Issue by AGenchev** [bluerobotics/BlueESC#5]
Hello. I was looking for an ingenious design which would me allow to ditch the gate drivers I use, hence looked at the schematic in  https://github.com/bluerobotics/BlueESC/raw/master/BlueESC/BlueESC.pdf
But quickly realized that it will not perform on a par with the gate drivers (at least for the high side NMOSFETs).
The upper FETs are N-channel. They turn on with <b>positive</b> voltage on the gate relative to the source.
Watching the schematic in the https://github.com/bluerobotics/BlueESC/raw/master/BlueESC/BlueESC.pdf you can see that the upper FETs can get positive voltage on their gates from the high side of the capacitors via 100 Ω <b>plus 2.2 kΩ</b> resistors when the NPN transistors are OFF. This mean that the total resistance on this path is 2.3 kΩ, so the turn on RC constant is 10-20 times longer. E.t. instead of 100 nS, it goes at least to 1000 nS. This should lead to more heat generated by the upper FETs (if the charging pumps work as intended and supply higher than Vcc voltage to turn on the upper FETs).  You should use either more sophisticated push-pull high side gate driver or use an IC gate driver (which of course will make the BOM with higher cost).

**Comment by Williangalvani** [comment]
As this repository is being archived and will see no further development, all issues are being closed.
